version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: time_tracker_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "6432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: